version: '3.9'

services:
  dashboard:
    build: ./dashboard-new
    ports:
      - "3000:3000"
    environment:
      - ROBLE_BASE_HOST=${ROBLE_BASE_HOST}
      - ROBLE_CONTRACT=${ROBLE_CONTRACT}
    networks:
      - microservices-net
    depends_on:
      - microservice-template

  microservice-template:
    build: ./microservice-template
    ports:
      - "5000:5000"
    environment:
      - ROBLE_BASE_HOST=${ROBLE_BASE_HOST}
      - ROBLE_CONTRACT=${ROBLE_CONTRACT}
      - SERVICE_NAME=template-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  docker_sock: